[project]
name = "repl-nix-stockpulse"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "nltk>=3.9.1",
    "pandas>=2.2.3",
    "plotly>=5.24.1",
    "streamlit>=1.41.1",
    "textblob>=0.18.0.post0",
    "yfinance>=0.2.51",
]
