[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
# Light mode colors
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

# Dark mode will be handled via custom CSS in the app